version: '3.1'

services:
  bot:
    build:
      context: ./
    container_name: discord-bot
    volumes:
      - ./:/app
    env_file:
      - .env
    hostname: discord-bot
    working_dir: /app
    entrypoint: ['python', '/app/main.py']

  db:
    image: postgres:10.5
    container_name: discord-db
    ports:
      - 5432:5432
    volumes:
      #- ./postgres/init:/docker-entrypoint-initdb.d
      # docker volume create pgsql-data
      - pgsql-data:/var/lib/postgresql/
    env_file:
      - .env
    environment:
      POSTGRES_DB: dsgame
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: discord-db
    #restart: always

volumes:
  pgsql-data:
    external: true
