"""Add imp02,03 and win_flg02, win_flg03 cols to results table

Revision ID: dc08c503dc3b
Revises: 925304b8e52f
Create Date: 2021-03-05 06:32:29.404152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc08c503dc3b'
down_revision = '925304b8e52f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('impostor02', sa.String(length=50), nullable=True))
    op.add_column('results', sa.Column('impostor03', sa.String(length=50), nullable=True))
    op.add_column('results', sa.Column('win_flg02', sa.Boolean(), nullable=True))
    op.add_column('results', sa.Column('win_flg03', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'win_flg03')
    op.drop_column('results', 'win_flg02')
    op.drop_column('results', 'impostor03')
    op.drop_column('results', 'impostor02')
    # ### end Alembic commands ###
